/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Invest } from "./Invest";
export * as factories from "./factories";
export { Invest__factory } from "./factories/Invest__factory";
